### ISSUE TITLE
Podcast missing from search

### ISSUE THREAD

**Issue by beenhazed** [shahruz/unofficialrss#5]
The podcast "Hello from the Magic Tavern" (show id 1001548) does not exist on using the search function on the website, yet does exist on stitcher search. Also, all of the "spin-off" podcasts of "Hello from the Magic Tavern" display on search. This behavior seems new, or may have begun after switching from the old url to v2.

**Comment by j0be** [comment]
This site isn't designed to download non-premium feeds.

Just use their public feed: https://rss.art19.com/hello-from-magic-tavern

**Comment by beenhazed** [comment]
Okay, thank you!
